name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: ./srcs/requirements/nginx/Dockerfile
    ports:
     - 443:443
    restart: always
    networks:
      - frontend
    volumes:
     - wp_volume:/var/www/html
  wordpress:
    container_name: wordpress
    build:
      context: ../
      dockerfile: ./srcs/requirements/wordpress/Dockerfile
      secrets:
       - db_secrets
    restart: always
    depends_on:
      mariadb:
        condition: service_started
    env_file:
      - ../.env
    volumes:
     - wp_volume:/var/www/html
    networks:
      - frontend
      - backend
    ports:
     - 9000
    secrets:
     - wp_secrets
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      secrets:
       - db_secrets
    restart: always
    env_file:
      - ../.env
    volumes:
     - db_volume:/var/lib/mysql
    networks:
      - backend
    ports:
     - 3306

networks:
  frontend:
  backend:
volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ikulik/data/mariadb
      o: bind
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ikulik/data/wordpress
      o: bind
secrets:
  db_secrets:
    file: ../.secrets/db_secrets
  wp_secrets:
    file: ../.secrets/wp_secrets
