name: inception

services:
  nginx:
    container_name: nginx
    image: nginx:1.0
    build:
      context: ./requirements/nginx
      secrets:
       - ssh_secrets
    ports:
     - 443:443
    restart: always
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_started
    networks:
      - frontend
    volumes:
     - wp_volume:/var/www/html
  wordpress:
    container_name: wordpress
    image: wordpress:1.0
    build:
      context: ./requirements/wordpress
      secrets:
       - db_secrets
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
     - wp_volume:/var/www/html
    networks:
      - frontend
      - backend
    ports:
     - 9000
    secrets:
     - wp_secrets
  mariadb:
    container_name: mariadb
    image: mariadb:1.0
    build:
      context: ./requirements/mariadb
      secrets:
       - db_secrets
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-w", "1", "127.0.0.1", "3306"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
    env_file:
      - .env
    volumes:
     - db_volume:/var/lib/mysql
    networks:
      - backend
    ports:
     - 3306

networks:
  frontend:
  backend:
volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ikulik/data/mariadb
      o: bind
  wp_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/ikulik/data/wordpress
      o: bind
secrets:
  db_secrets:
    file: ../.secrets/db_secrets
  wp_secrets:
    file: ../.secrets/wp_secrets
  ssh_secrets:
    file: ../.secrets/ssh_secrets
